### ISSUE TITLE
Vis 6.0.0

### ISSUE THREAD

**Issue by Alfhir** [zewa666/aurelia-store-examples#8]
Could you please bump the Vis example to Vis v6.0.0?
 I tried to do so with a Webpack-Project, but failed miserably.
Thanks for the great examples!

**Comment by zewa666** [comment]
Mind providing a PR for that?

**Comment by Alfhir** [comment]
Sorry, I don't know how to import the needed classes, since they changed their modules and i couldn't find any current documentation.

**Comment by zewa666** [comment]
Ah ok, I'll take a look and see what I can do about it

**Comment by zewa666** [comment]
Hey there @Alfhir,

I think I found the reason for your problems. It seems that with v6 vis is splitted into multiple components. So instead of `npm install vis` its now `npm install vis-network` in our case of using the network part.

I've updated the sample and also added the hover effect in order to show how to import the related css file from the package.

Please let me know whether this works for you. Btw. just to make sure try to clean node_modules folder if something doesn't go well after your npm install

**Comment by Alfhir** [comment]
Hi @zewa666,

thank you so much. I´ll try it out, as soon as i get home!

**Comment by Alfhir** [comment]
Hello @Zewa666,

it's working fine, including the hover-effect. 
I didn't see, that installing _"vis-network": "^6.0.0"_ and _import vis from 'vis-network'_ would pull in all dependencies, including DataSet from 'vis-data'. I had tried to install vis-network and vis-data and import them via import { Dataset } from 'vis-data' and import { Network } from 'vis-network' - obviously w/o success. 
Thanks again!
